from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from swagger_client.api.about_api import AboutApi
from swagger_client.api.cloud_account_api import CloudAccountApi
from swagger_client.api.compute_api import ComputeApi
from swagger_client.api.data_collector_api import DataCollectorApi
from swagger_client.api.disk_api import DiskApi
from swagger_client.api.fabric_aws_volume_types_api import FabricAWSVolumeTypesApi
from swagger_client.api.fabric_azure_storage_account_api import FabricAzureStorageAccountApi
from swagger_client.api.fabric_flavors_api import FabricFlavorsApi
from swagger_client.api.fabric_images_api import FabricImagesApi
from swagger_client.api.fabric_network_api import FabricNetworkApi
from swagger_client.api.fabric_v_sphere_datastore_api import FabricVSphereDatastoreApi
from swagger_client.api.fabric_v_sphere_storage_policies_api import FabricVSphereStoragePoliciesApi
from swagger_client.api.flavor_profile_api import FlavorProfileApi
from swagger_client.api.flavors_api import FlavorsApi
from swagger_client.api.image_profile_api import ImageProfileApi
from swagger_client.api.images_api import ImagesApi
from swagger_client.api.load_balancer_api import LoadBalancerApi
from swagger_client.api.location_api import LocationApi
from swagger_client.api.login_api import LoginApi
from swagger_client.api.network_api import NetworkApi
from swagger_client.api.network_profile_api import NetworkProfileApi
from swagger_client.api.project_api import ProjectApi
from swagger_client.api.request_api import RequestApi
from swagger_client.api.security_group_api import SecurityGroupApi
from swagger_client.api.storage_profile_api import StorageProfileApi
from swagger_client.api.tags_api import TagsApi
