# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.fabric_azure_storage_account_api import FabricAzureStorageAccountApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFabricAzureStorageAccountApi(unittest.TestCase):
    """FabricAzureStorageAccountApi unit test stubs"""

    def setUp(self):
        self.api = api.fabric_azure_storage_account_api.FabricAzureStorageAccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_fabric_azure_storage_account(self):
        """Test case for get_fabric_azure_storage_account

        Get fabric Azure storage account  # noqa: E501
        """
        pass

    def test_get_fabric_azure_storage_accounts(self):
        """Test case for get_fabric_azure_storage_accounts

        Get fabric Azure storage accounts  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
