# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.flavor_profile_api import FlavorProfileApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFlavorProfileApi(unittest.TestCase):
    """FlavorProfileApi unit test stubs"""

    def setUp(self):
        self.api = api.flavor_profile_api.FlavorProfileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_flavor_profile(self):
        """Test case for create_flavor_profile

        Create flavor profile  # noqa: E501
        """
        pass

    def test_delete_flavor_profile(self):
        """Test case for delete_flavor_profile

        Delete flavor profile  # noqa: E501
        """
        pass

    def test_get_flavor_profile(self):
        """Test case for get_flavor_profile

        Get flavor profile  # noqa: E501
        """
        pass

    def test_get_flavor_profiles(self):
        """Test case for get_flavor_profiles

        Get flavor profile  # noqa: E501
        """
        pass

    def test_update_flavor_profile(self):
        """Test case for update_flavor_profile

        Update flavor profile  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
