# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.project_api import ProjectApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectApi(unittest.TestCase):
    """ProjectApi unit test stubs"""

    def setUp(self):
        self.api = api.project_api.ProjectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_project(self):
        """Test case for create_project

        Create project  # noqa: E501
        """
        pass

    def test_delete_project(self):
        """Test case for delete_project

        Delete project  # noqa: E501
        """
        pass

    def test_get_project(self):
        """Test case for get_project

        Get project  # noqa: E501
        """
        pass

    def test_get_project_resource_metadata(self):
        """Test case for get_project_resource_metadata

        Get project resource metadata  # noqa: E501
        """
        pass

    def test_get_projects(self):
        """Test case for get_projects

        Get projects  # noqa: E501
        """
        pass

    def test_update_project(self):
        """Test case for update_project

        Update project  # noqa: E501
        """
        pass

    def test_update_project_resource_metadata(self):
        """Test case for update_project_resource_metadata

        Update project resource metadata  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
