# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.fabric_flavors_api import FabricFlavorsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFabricFlavorsApi(unittest.TestCase):
    """FabricFlavorsApi unit test stubs"""

    def setUp(self):
        self.api = api.fabric_flavors_api.FabricFlavorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_fabric_flavors(self):
        """Test case for get_fabric_flavors

        Get fabric flavors  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
