# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.project_resource_metadata_specification import ProjectResourceMetadataSpecification  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectResourceMetadataSpecification(unittest.TestCase):
    """ProjectResourceMetadataSpecification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectResourceMetadataSpecification(self):
        """Test ProjectResourceMetadataSpecification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.project_resource_metadata_specification.ProjectResourceMetadataSpecification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
