# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.fabric_v_sphere_datastore_api import FabricVSphereDatastoreApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFabricVSphereDatastoreApi(unittest.TestCase):
    """FabricVSphereDatastoreApi unit test stubs"""

    def setUp(self):
        self.api = api.fabric_v_sphere_datastore_api.FabricVSphereDatastoreApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_fabric_v_sphere_datastore(self):
        """Test case for get_fabric_v_sphere_datastore

        Get fabric vSphere datastore  # noqa: E501
        """
        pass

    def test_get_fabric_v_sphere_datastores(self):
        """Test case for get_fabric_v_sphere_datastores

        Get fabric vSphere datastores  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
