# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.images_api import ImagesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestImagesApi(unittest.TestCase):
    """ImagesApi unit test stubs"""

    def setUp(self):
        self.api = api.images_api.ImagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_images(self):
        """Test case for get_images

        Get images  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
