# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.cloud_account_api import CloudAccountApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCloudAccountApi(unittest.TestCase):
    """CloudAccountApi unit test stubs"""

    def setUp(self):
        self.api = api.cloud_account_api.CloudAccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_aws_cloud_account(self):
        """Test case for create_aws_cloud_account

        Create an AWS cloud account  # noqa: E501
        """
        pass

    def test_create_azure_cloud_account(self):
        """Test case for create_azure_cloud_account

        Create an Azure cloud account  # noqa: E501
        """
        pass

    def test_create_cloud_account(self):
        """Test case for create_cloud_account

        Create a cloud account  # noqa: E501
        """
        pass

    def test_create_gcp_cloud_account(self):
        """Test case for create_gcp_cloud_account

        Create an GCP cloud account  # noqa: E501
        """
        pass

    def test_create_nsx_t_cloud_account(self):
        """Test case for create_nsx_t_cloud_account

        Create a NSX-T cloud account  # noqa: E501
        """
        pass

    def test_create_nsx_v_cloud_account(self):
        """Test case for create_nsx_v_cloud_account

        Create a NSX-V cloud account  # noqa: E501
        """
        pass

    def test_create_v_sphere_cloud_account(self):
        """Test case for create_v_sphere_cloud_account

        Create a vSphere cloud account  # noqa: E501
        """
        pass

    def test_delete_aws_cloud_account(self):
        """Test case for delete_aws_cloud_account

        Delete an AWS cloud account  # noqa: E501
        """
        pass

    def test_delete_azure_cloud_account(self):
        """Test case for delete_azure_cloud_account

        Delete an Azure Cloud Account  # noqa: E501
        """
        pass

    def test_delete_cloud_account(self):
        """Test case for delete_cloud_account

        Delete a cloud account  # noqa: E501
        """
        pass

    def test_delete_cloud_account_nsx_t(self):
        """Test case for delete_cloud_account_nsx_t

        Delete a NSX-T cloud account  # noqa: E501
        """
        pass

    def test_delete_cloud_account_nsx_v(self):
        """Test case for delete_cloud_account_nsx_v

        Delete a NSV-V cloud account  # noqa: E501
        """
        pass

    def test_delete_gcp_cloud_account(self):
        """Test case for delete_gcp_cloud_account

        Delete an GCP cloud account  # noqa: E501
        """
        pass

    def test_delete_v_sphere_cloud_account(self):
        """Test case for delete_v_sphere_cloud_account

        Delete a vSphere cloud account  # noqa: E501
        """
        pass

    def test_enumerate_aws_regions(self):
        """Test case for enumerate_aws_regions

        Get the available regions for specified AWS cloud account  # noqa: E501
        """
        pass

    def test_enumerate_azure_regions(self):
        """Test case for enumerate_azure_regions

        Get the available regions for specified Azure cloud account  # noqa: E501
        """
        pass

    def test_enumerate_gcp_regions(self):
        """Test case for enumerate_gcp_regions

        Get the available regions for specified GCP cloud account  # noqa: E501
        """
        pass

    def test_enumerate_regions(self):
        """Test case for enumerate_regions

        Get the available regions for specified cloud account  # noqa: E501
        """
        pass

    def test_enumerate_v_sphere_regions(self):
        """Test case for enumerate_v_sphere_regions

        Get the available regions for specified vSphere cloud account  # noqa: E501
        """
        pass

    def test_get_aws_cloud_account(self):
        """Test case for get_aws_cloud_account

        Get an AWS cloud account  # noqa: E501
        """
        pass

    def test_get_aws_cloud_accounts(self):
        """Test case for get_aws_cloud_accounts

        Get AWS cloud accounts  # noqa: E501
        """
        pass

    def test_get_azure_cloud_account(self):
        """Test case for get_azure_cloud_account

        Get an Azure Cloud Account  # noqa: E501
        """
        pass

    def test_get_azure_cloud_accounts(self):
        """Test case for get_azure_cloud_accounts

        Get Azure cloud accounts  # noqa: E501
        """
        pass

    def test_get_cloud_account(self):
        """Test case for get_cloud_account

        Get cloud account  # noqa: E501
        """
        pass

    def test_get_cloud_accounts(self):
        """Test case for get_cloud_accounts

        Get cloud accounts  # noqa: E501
        """
        pass

    def test_get_gcp_cloud_account(self):
        """Test case for get_gcp_cloud_account

        Get an GCP cloud account  # noqa: E501
        """
        pass

    def test_get_gcp_cloud_accounts(self):
        """Test case for get_gcp_cloud_accounts

        Get GCP cloud accounts  # noqa: E501
        """
        pass

    def test_get_nsx_t_cloud_account(self):
        """Test case for get_nsx_t_cloud_account

        Get an NSX-T cloud account  # noqa: E501
        """
        pass

    def test_get_nsx_t_cloud_accounts(self):
        """Test case for get_nsx_t_cloud_accounts

        Get NSX-T cloud accounts  # noqa: E501
        """
        pass

    def test_get_nsx_v_cloud_account(self):
        """Test case for get_nsx_v_cloud_account

        Get an NSX-V cloud account  # noqa: E501
        """
        pass

    def test_get_nsx_v_cloud_accounts(self):
        """Test case for get_nsx_v_cloud_accounts

        Get NSX-V cloud accounts  # noqa: E501
        """
        pass

    def test_get_v_sphere_cloud_account(self):
        """Test case for get_v_sphere_cloud_account

        Get an vSphere cloud account  # noqa: E501
        """
        pass

    def test_get_v_sphere_cloud_accounts(self):
        """Test case for get_v_sphere_cloud_accounts

        Get vSphere cloud accounts  # noqa: E501
        """
        pass

    def test_update_aws_cloud_account(self):
        """Test case for update_aws_cloud_account

        Update AWS cloud account  # noqa: E501
        """
        pass

    def test_update_azure_cloud_account(self):
        """Test case for update_azure_cloud_account

        Update Azure cloud account  # noqa: E501
        """
        pass

    def test_update_cloud_account(self):
        """Test case for update_cloud_account

        Update CloudAccount  # noqa: E501
        """
        pass

    def test_update_gcp_cloud_account(self):
        """Test case for update_gcp_cloud_account

        Update GCP cloud account  # noqa: E501
        """
        pass

    def test_update_nsx_t_cloud_account(self):
        """Test case for update_nsx_t_cloud_account

        Update NSX-T cloud account  # noqa: E501
        """
        pass

    def test_update_nsx_v_cloud_account(self):
        """Test case for update_nsx_v_cloud_account

        Update NSX-V cloud account  # noqa: E501
        """
        pass

    def test_update_v_sphere_cloud_account(self):
        """Test case for update_v_sphere_cloud_account

        Update vSphere cloud account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
