# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.tags_api import TagsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self):
        self.api = api.tags_api.TagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_tags(self):
        """Test case for get_tags

        Get tags  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
