# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.csp_login_specification import CspLoginSpecification  # noqa: E501
from swagger_client.rest import ApiException


class TestCspLoginSpecification(unittest.TestCase):
    """CspLoginSpecification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCspLoginSpecification(self):
        """Test CspLoginSpecification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.csp_login_specification.CspLoginSpecification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
