# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.about_api import AboutApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAboutApi(unittest.TestCase):
    """AboutApi unit test stubs"""

    def setUp(self):
        self.api = api.about_api.AboutApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_about_page(self):
        """Test case for get_about_page

        Get about page  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
