# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.storage_profile_api import StorageProfileApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStorageProfileApi(unittest.TestCase):
    """StorageProfileApi unit test stubs"""

    def setUp(self):
        self.api = api.storage_profile_api.StorageProfileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_aws_storage_profile(self):
        """Test case for create_aws_storage_profile

        Create AWS storage profile  # noqa: E501
        """
        pass

    def test_create_azure_storage_profile(self):
        """Test case for create_azure_storage_profile

        Create Azure storage profile  # noqa: E501
        """
        pass

    def test_create_storage_profile(self):
        """Test case for create_storage_profile

        Create storage profile  # noqa: E501
        """
        pass

    def test_create_v_sphere_storage_profile(self):
        """Test case for create_v_sphere_storage_profile

        Create vSphere storage profile  # noqa: E501
        """
        pass

    def test_delete_aws_storage_profile(self):
        """Test case for delete_aws_storage_profile

        Delete AWS storage profile  # noqa: E501
        """
        pass

    def test_delete_azure_storage_profile(self):
        """Test case for delete_azure_storage_profile

        Delete Azure storage profile  # noqa: E501
        """
        pass

    def test_delete_storage_profile(self):
        """Test case for delete_storage_profile

        Delete storage profile  # noqa: E501
        """
        pass

    def test_delete_v_sphere_storage_profile(self):
        """Test case for delete_v_sphere_storage_profile

        Delete vSphere storage profile  # noqa: E501
        """
        pass

    def test_get_aws_storage_profile(self):
        """Test case for get_aws_storage_profile

        Get AWS storage profile  # noqa: E501
        """
        pass

    def test_get_aws_storage_profiles(self):
        """Test case for get_aws_storage_profiles

        Get AWS storage profiles  # noqa: E501
        """
        pass

    def test_get_azure_storage_profile(self):
        """Test case for get_azure_storage_profile

        Get Azure storage profile  # noqa: E501
        """
        pass

    def test_get_azure_storage_profiles(self):
        """Test case for get_azure_storage_profiles

        Get Azure storage profiles  # noqa: E501
        """
        pass

    def test_get_storage_profile(self):
        """Test case for get_storage_profile

        Get storage profile  # noqa: E501
        """
        pass

    def test_get_storage_profiles(self):
        """Test case for get_storage_profiles

        Get storage profiles  # noqa: E501
        """
        pass

    def test_get_v_sphere_storage_profile(self):
        """Test case for get_v_sphere_storage_profile

        Get vSphere storage profile  # noqa: E501
        """
        pass

    def test_get_v_sphere_storage_profiles(self):
        """Test case for get_v_sphere_storage_profiles

        Get vSphere storage profiles  # noqa: E501
        """
        pass

    def test_replace_storage_profile(self):
        """Test case for replace_storage_profile

        Replace storage profile  # noqa: E501
        """
        pass

    def test_update_aws_storage_profile(self):
        """Test case for update_aws_storage_profile

        Update AWS storage profile  # noqa: E501
        """
        pass

    def test_update_azure_storage_profile(self):
        """Test case for update_azure_storage_profile

        Update Azure storage profile  # noqa: E501
        """
        pass

    def test_update_v_sphere_storage_profile(self):
        """Test case for update_v_sphere_storage_profile

        Update vSphere storage profile  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
