# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.update_machine_specification import UpdateMachineSpecification  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateMachineSpecification(unittest.TestCase):
    """UpdateMachineSpecification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateMachineSpecification(self):
        """Test UpdateMachineSpecification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_machine_specification.UpdateMachineSpecification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
