# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.update_cloud_account_azure_specification import UpdateCloudAccountAzureSpecification  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateCloudAccountAzureSpecification(unittest.TestCase):
    """UpdateCloudAccountAzureSpecification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateCloudAccountAzureSpecification(self):
        """Test UpdateCloudAccountAzureSpecification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_cloud_account_azure_specification.UpdateCloudAccountAzureSpecification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
