# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.snapshot import Snapshot  # noqa: E501
from swagger_client.rest import ApiException


class TestSnapshot(unittest.TestCase):
    """Snapshot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSnapshot(self):
        """Test Snapshot"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.snapshot.Snapshot()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
