# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.data_collector_api import DataCollectorApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDataCollectorApi(unittest.TestCase):
    """DataCollectorApi unit test stubs"""

    def setUp(self):
        self.api = api.data_collector_api.DataCollectorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_data_collector(self):
        """Test case for create_data_collector

        Create Data collector  # noqa: E501
        """
        pass

    def test_delete_data_collector(self):
        """Test case for delete_data_collector

        Delete Data Collector  # noqa: E501
        """
        pass

    def test_get_data_collector(self):
        """Test case for get_data_collector

        Get Data Collector  # noqa: E501
        """
        pass

    def test_get_data_collectors(self):
        """Test case for get_data_collectors

        Get Data Collectors  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
