# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.load_balancer_api import LoadBalancerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLoadBalancerApi(unittest.TestCase):
    """LoadBalancerApi unit test stubs"""

    def setUp(self):
        self.api = api.load_balancer_api.LoadBalancerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_load_balancer(self):
        """Test case for create_load_balancer

        Create load balancer  # noqa: E501
        """
        pass

    def test_delete_load_balancer(self):
        """Test case for delete_load_balancer

        Delete load balancer  # noqa: E501
        """
        pass

    def test_delete_load_balancer_operation(self):
        """Test case for delete_load_balancer_operation

        Delete operation for load balancer  # noqa: E501
        """
        pass

    def test_get_load_balancer(self):
        """Test case for get_load_balancer

        Get load balancer  # noqa: E501
        """
        pass

    def test_get_load_balancers(self):
        """Test case for get_load_balancers

        Get load balancers  # noqa: E501
        """
        pass

    def test_scale_load_balancer(self):
        """Test case for scale_load_balancer

        Scale operation for load balancer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
