# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.image_profile_api import ImageProfileApi  # noqa: E501
from swagger_client.rest import ApiException


class TestImageProfileApi(unittest.TestCase):
    """ImageProfileApi unit test stubs"""

    def setUp(self):
        self.api = api.image_profile_api.ImageProfileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_image_profile(self):
        """Test case for create_image_profile

        Create image profile  # noqa: E501
        """
        pass

    def test_delete_image_profile(self):
        """Test case for delete_image_profile

        Delete image profile  # noqa: E501
        """
        pass

    def test_get_image_profile(self):
        """Test case for get_image_profile

        Get image profile  # noqa: E501
        """
        pass

    def test_get_image_profiles(self):
        """Test case for get_image_profiles

        Get image profile  # noqa: E501
        """
        pass

    def test_update_image_profile(self):
        """Test case for update_image_profile

        Update image profile  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
