# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.data_collector_registration import DataCollectorRegistration  # noqa: E501
from swagger_client.rest import ApiException


class TestDataCollectorRegistration(unittest.TestCase):
    """DataCollectorRegistration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataCollectorRegistration(self):
        """Test DataCollectorRegistration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.data_collector_registration.DataCollectorRegistration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
