# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.disk_api import DiskApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDiskApi(unittest.TestCase):
    """DiskApi unit test stubs"""

    def setUp(self):
        self.api = api.disk_api.DiskApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_attach_machine_disk(self):
        """Test case for attach_machine_disk

        Attach machine disk  # noqa: E501
        """
        pass

    def test_create_block_device(self):
        """Test case for create_block_device

        Create BlockDevice  # noqa: E501
        """
        pass

    def test_delete_block_device(self):
        """Test case for delete_block_device

        Delete a BlockDevice  # noqa: E501
        """
        pass

    def test_delete_machine_disk(self):
        """Test case for delete_machine_disk

        Delete machine disk  # noqa: E501
        """
        pass

    def test_get_block_device(self):
        """Test case for get_block_device

        Get BlockDevice  # noqa: E501
        """
        pass

    def test_get_block_devices(self):
        """Test case for get_block_devices

        Get BlockDevices  # noqa: E501
        """
        pass

    def test_get_machine_disk(self):
        """Test case for get_machine_disk

        Get a machine disk  # noqa: E501
        """
        pass

    def test_get_machine_disks(self):
        """Test case for get_machine_disks

        Get machine disks  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
