# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.compute_api import ComputeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestComputeApi(unittest.TestCase):
    """ComputeApi unit test stubs"""

    def setUp(self):
        self.api = api.compute_api.ComputeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_attach_machine_disk(self):
        """Test case for attach_machine_disk

        Attach machine disk  # noqa: E501
        """
        pass

    def test_create_machine(self):
        """Test case for create_machine

        Create machine  # noqa: E501
        """
        pass

    def test_create_machine_snapshot(self):
        """Test case for create_machine_snapshot

        Create snapshot operation for machine  # noqa: E501
        """
        pass

    def test_delete_machine(self):
        """Test case for delete_machine

        Delete Machine  # noqa: E501
        """
        pass

    def test_delete_machine_disk(self):
        """Test case for delete_machine_disk

        Delete machine disk  # noqa: E501
        """
        pass

    def test_delete_machine_snapshot(self):
        """Test case for delete_machine_snapshot

        Delete snapshot operation for machine  # noqa: E501
        """
        pass

    def test_get_machine(self):
        """Test case for get_machine

        Get machine  # noqa: E501
        """
        pass

    def test_get_machine_disk(self):
        """Test case for get_machine_disk

        Get a machine disk  # noqa: E501
        """
        pass

    def test_get_machine_disks(self):
        """Test case for get_machine_disks

        Get machine disks  # noqa: E501
        """
        pass

    def test_get_machine_network_interface(self):
        """Test case for get_machine_network_interface

        Get machine network interface  # noqa: E501
        """
        pass

    def test_get_machine_snapshots(self):
        """Test case for get_machine_snapshots

        Get machine snapshots information  # noqa: E501
        """
        pass

    def test_get_machines(self):
        """Test case for get_machines

        Get machines  # noqa: E501
        """
        pass

    def test_power_off_machine(self):
        """Test case for power_off_machine

        Power-off operation for machine  # noqa: E501
        """
        pass

    def test_power_on_machine(self):
        """Test case for power_on_machine

        Power-on operation for machine  # noqa: E501
        """
        pass

    def test_reboot_machine(self):
        """Test case for reboot_machine

        Reboot operation for machine  # noqa: E501
        """
        pass

    def test_reset_machine(self):
        """Test case for reset_machine

        Reset operation for machine  # noqa: E501
        """
        pass

    def test_resize_machine(self):
        """Test case for resize_machine

        Resize operation for machine  # noqa: E501
        """
        pass

    def test_restart_machine(self):
        """Test case for restart_machine

        Restart operation for machine  # noqa: E501
        """
        pass

    def test_revert_machine_snapshot(self):
        """Test case for revert_machine_snapshot

        Revert snapshot operation for machine  # noqa: E501
        """
        pass

    def test_shutdown_machine(self):
        """Test case for shutdown_machine

        Shut down operation for machine  # noqa: E501
        """
        pass

    def test_suspend_machine(self):
        """Test case for suspend_machine

        Suspend operation for machine  # noqa: E501
        """
        pass

    def test_update_machine(self):
        """Test case for update_machine

        Update machine.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
