# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.network_profile_api import NetworkProfileApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNetworkProfileApi(unittest.TestCase):
    """NetworkProfileApi unit test stubs"""

    def setUp(self):
        self.api = api.network_profile_api.NetworkProfileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_network_profile(self):
        """Test case for create_network_profile

        Create network profile  # noqa: E501
        """
        pass

    def test_delete_network_profile(self):
        """Test case for delete_network_profile

        Delete network profile  # noqa: E501
        """
        pass

    def test_get_network_profile(self):
        """Test case for get_network_profile

        Get network profile  # noqa: E501
        """
        pass

    def test_get_network_profiles(self):
        """Test case for get_network_profiles

        Get network profiles  # noqa: E501
        """
        pass

    def test_update_network_profile(self):
        """Test case for update_network_profile

        Update network profile  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
