# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.network_api import NetworkApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNetworkApi(unittest.TestCase):
    """NetworkApi unit test stubs"""

    def setUp(self):
        self.api = api.network_api.NetworkApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_network(self):
        """Test case for create_network

        Create network  # noqa: E501
        """
        pass

    def test_delete_network(self):
        """Test case for delete_network

        Delete a network  # noqa: E501
        """
        pass

    def test_get_machine_network_interface(self):
        """Test case for get_machine_network_interface

        Get machine network interface  # noqa: E501
        """
        pass

    def test_get_network(self):
        """Test case for get_network

        Get network  # noqa: E501
        """
        pass

    def test_get_network_domain(self):
        """Test case for get_network_domain

        Get network domain  # noqa: E501
        """
        pass

    def test_get_network_domains(self):
        """Test case for get_network_domains

        Get network domains  # noqa: E501
        """
        pass

    def test_get_networks(self):
        """Test case for get_networks

        Get networks  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
