# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.fabric_network_api import FabricNetworkApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFabricNetworkApi(unittest.TestCase):
    """FabricNetworkApi unit test stubs"""

    def setUp(self):
        self.api = api.fabric_network_api.FabricNetworkApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_fabric_network(self):
        """Test case for get_fabric_network

        Get fabric network  # noqa: E501
        """
        pass

    def test_get_fabric_networks(self):
        """Test case for get_fabric_networks

        Get fabric networks  # noqa: E501
        """
        pass

    def test_update_fabric_network(self):
        """Test case for update_fabric_network

        Update fabric network.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
