# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.fabric_aws_volume_types_api import FabricAWSVolumeTypesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFabricAWSVolumeTypesApi(unittest.TestCase):
    """FabricAWSVolumeTypesApi unit test stubs"""

    def setUp(self):
        self.api = api.fabric_aws_volume_types_api.FabricAWSVolumeTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_fabric_aws_volume_types(self):
        """Test case for get_fabric_aws_volume_types

        Get fabric AWS volume types  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
