# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.fabric_v_sphere_storage_policies_api import FabricVSphereStoragePoliciesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFabricVSphereStoragePoliciesApi(unittest.TestCase):
    """FabricVSphereStoragePoliciesApi unit test stubs"""

    def setUp(self):
        self.api = api.fabric_v_sphere_storage_policies_api.FabricVSphereStoragePoliciesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_fabric_v_sphere_storage_policies(self):
        """Test case for get_fabric_v_sphere_storage_policies

        Get fabric vSphere storage polices  # noqa: E501
        """
        pass

    def test_get_fabric_v_sphere_storage_policy(self):
        """Test case for get_fabric_v_sphere_storage_policy

        Get fabric vSphere storage policy  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
