# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.location_api import LocationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLocationApi(unittest.TestCase):
    """LocationApi unit test stubs"""

    def setUp(self):
        self.api = api.location_api.LocationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_zone(self):
        """Test case for create_zone

        Create zone  # noqa: E501
        """
        pass

    def test_delete_zone(self):
        """Test case for delete_zone

        Delete a zone  # noqa: E501
        """
        pass

    def test_get_region(self):
        """Test case for get_region

        Get Region  # noqa: E501
        """
        pass

    def test_get_regions(self):
        """Test case for get_regions

        Get regions  # noqa: E501
        """
        pass

    def test_get_zone(self):
        """Test case for get_zone

        Get zone  # noqa: E501
        """
        pass

    def test_get_zones(self):
        """Test case for get_zones

        Get zones  # noqa: E501
        """
        pass

    def test_update_zone(self):
        """Test case for update_zone

        Update zone  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
