# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.href import Href  # noqa: F401,E501
from swagger_client.models.tag import Tag  # noqa: F401,E501


class AwsStorageProfile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'created_at': 'str',
        'updated_at': 'str',
        'owner': 'str',
        'organization_id': 'str',
        'org_id': 'str',
        'links': 'dict(str, Href)',
        'name': 'str',
        'description': 'str',
        'default_item': 'bool',
        'supports_encryption': 'bool',
        'tags': 'list[Tag]',
        'device_type': 'str',
        'volume_type': 'str',
        'iops': 'str',
        'external_region_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'created_at': 'createdAt',
        'updated_at': 'updatedAt',
        'owner': 'owner',
        'organization_id': 'organizationId',
        'org_id': 'orgId',
        'links': '_links',
        'name': 'name',
        'description': 'description',
        'default_item': 'defaultItem',
        'supports_encryption': 'supportsEncryption',
        'tags': 'tags',
        'device_type': 'deviceType',
        'volume_type': 'volumeType',
        'iops': 'iops',
        'external_region_id': 'externalRegionId'
    }

    def __init__(self, id=None, created_at=None, updated_at=None, owner=None, organization_id=None, org_id=None, links=None, name=None, description=None, default_item=None, supports_encryption=None, tags=None, device_type=None, volume_type=None, iops=None, external_region_id=None):  # noqa: E501
        """AwsStorageProfile - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._created_at = None
        self._updated_at = None
        self._owner = None
        self._organization_id = None
        self._org_id = None
        self._links = None
        self._name = None
        self._description = None
        self._default_item = None
        self._supports_encryption = None
        self._tags = None
        self._device_type = None
        self._volume_type = None
        self._iops = None
        self._external_region_id = None
        self.discriminator = None
        self.id = id
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at
        if owner is not None:
            self.owner = owner
        if organization_id is not None:
            self.organization_id = organization_id
        if org_id is not None:
            self.org_id = org_id
        self.links = links
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        self.default_item = default_item
        if supports_encryption is not None:
            self.supports_encryption = supports_encryption
        if tags is not None:
            self.tags = tags
        if device_type is not None:
            self.device_type = device_type
        if volume_type is not None:
            self.volume_type = volume_type
        if iops is not None:
            self.iops = iops
        if external_region_id is not None:
            self.external_region_id = external_region_id

    @property
    def id(self):
        """Gets the id of this AwsStorageProfile.  # noqa: E501

        The id of this resource instance  # noqa: E501

        :return: The id of this AwsStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AwsStorageProfile.

        The id of this resource instance  # noqa: E501

        :param id: The id of this AwsStorageProfile.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def created_at(self):
        """Gets the created_at of this AwsStorageProfile.  # noqa: E501

        Date when the entity was created. The date is in ISO 6801 and UTC.  # noqa: E501

        :return: The created_at of this AwsStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this AwsStorageProfile.

        Date when the entity was created. The date is in ISO 6801 and UTC.  # noqa: E501

        :param created_at: The created_at of this AwsStorageProfile.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this AwsStorageProfile.  # noqa: E501

        Date when the entity was last updated. The date is ISO 8601 and UTC.  # noqa: E501

        :return: The updated_at of this AwsStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this AwsStorageProfile.

        Date when the entity was last updated. The date is ISO 8601 and UTC.  # noqa: E501

        :param updated_at: The updated_at of this AwsStorageProfile.  # noqa: E501
        :type: str
        """

        self._updated_at = updated_at

    @property
    def owner(self):
        """Gets the owner of this AwsStorageProfile.  # noqa: E501

        Email of the user that owns the entity.  # noqa: E501

        :return: The owner of this AwsStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this AwsStorageProfile.

        Email of the user that owns the entity.  # noqa: E501

        :param owner: The owner of this AwsStorageProfile.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def organization_id(self):
        """Gets the organization_id of this AwsStorageProfile.  # noqa: E501

        This field is deprecated. Use orgId instead. The id of the organization this entity belongs to.  # noqa: E501

        :return: The organization_id of this AwsStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this AwsStorageProfile.

        This field is deprecated. Use orgId instead. The id of the organization this entity belongs to.  # noqa: E501

        :param organization_id: The organization_id of this AwsStorageProfile.  # noqa: E501
        :type: str
        """

        self._organization_id = organization_id

    @property
    def org_id(self):
        """Gets the org_id of this AwsStorageProfile.  # noqa: E501

        The id of the organization this entity belongs to.  # noqa: E501

        :return: The org_id of this AwsStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this AwsStorageProfile.

        The id of the organization this entity belongs to.  # noqa: E501

        :param org_id: The org_id of this AwsStorageProfile.  # noqa: E501
        :type: str
        """

        self._org_id = org_id

    @property
    def links(self):
        """Gets the links of this AwsStorageProfile.  # noqa: E501

        HATEOAS of the entity  # noqa: E501

        :return: The links of this AwsStorageProfile.  # noqa: E501
        :rtype: dict(str, Href)
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this AwsStorageProfile.

        HATEOAS of the entity  # noqa: E501

        :param links: The links of this AwsStorageProfile.  # noqa: E501
        :type: dict(str, Href)
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def name(self):
        """Gets the name of this AwsStorageProfile.  # noqa: E501

        A human-friendly name used as an identifier in APIs that support this option.  # noqa: E501

        :return: The name of this AwsStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AwsStorageProfile.

        A human-friendly name used as an identifier in APIs that support this option.  # noqa: E501

        :param name: The name of this AwsStorageProfile.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this AwsStorageProfile.  # noqa: E501

        A human-friendly description.  # noqa: E501

        :return: The description of this AwsStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this AwsStorageProfile.

        A human-friendly description.  # noqa: E501

        :param description: The description of this AwsStorageProfile.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def default_item(self):
        """Gets the default_item of this AwsStorageProfile.  # noqa: E501

        Indicates whether this storage profile is default or not..  # noqa: E501

        :return: The default_item of this AwsStorageProfile.  # noqa: E501
        :rtype: bool
        """
        return self._default_item

    @default_item.setter
    def default_item(self, default_item):
        """Sets the default_item of this AwsStorageProfile.

        Indicates whether this storage profile is default or not..  # noqa: E501

        :param default_item: The default_item of this AwsStorageProfile.  # noqa: E501
        :type: bool
        """
        if default_item is None:
            raise ValueError("Invalid value for `default_item`, must not be `None`")  # noqa: E501

        self._default_item = default_item

    @property
    def supports_encryption(self):
        """Gets the supports_encryption of this AwsStorageProfile.  # noqa: E501

        Indicates whether this storage profile supports encryption or not.  # noqa: E501

        :return: The supports_encryption of this AwsStorageProfile.  # noqa: E501
        :rtype: bool
        """
        return self._supports_encryption

    @supports_encryption.setter
    def supports_encryption(self, supports_encryption):
        """Sets the supports_encryption of this AwsStorageProfile.

        Indicates whether this storage profile supports encryption or not.  # noqa: E501

        :param supports_encryption: The supports_encryption of this AwsStorageProfile.  # noqa: E501
        :type: bool
        """

        self._supports_encryption = supports_encryption

    @property
    def tags(self):
        """Gets the tags of this AwsStorageProfile.  # noqa: E501

        A list of tags that represent the capabilities of this storage profile  # noqa: E501

        :return: The tags of this AwsStorageProfile.  # noqa: E501
        :rtype: list[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this AwsStorageProfile.

        A list of tags that represent the capabilities of this storage profile  # noqa: E501

        :param tags: The tags of this AwsStorageProfile.  # noqa: E501
        :type: list[Tag]
        """

        self._tags = tags

    @property
    def device_type(self):
        """Gets the device_type of this AwsStorageProfile.  # noqa: E501

        Indicates the type of storage device.  # noqa: E501

        :return: The device_type of this AwsStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._device_type

    @device_type.setter
    def device_type(self, device_type):
        """Sets the device_type of this AwsStorageProfile.

        Indicates the type of storage device.  # noqa: E501

        :param device_type: The device_type of this AwsStorageProfile.  # noqa: E501
        :type: str
        """

        self._device_type = device_type

    @property
    def volume_type(self):
        """Gets the volume_type of this AwsStorageProfile.  # noqa: E501

        Indicates the type of volume associated with type of storage device.  # noqa: E501

        :return: The volume_type of this AwsStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._volume_type

    @volume_type.setter
    def volume_type(self, volume_type):
        """Sets the volume_type of this AwsStorageProfile.

        Indicates the type of volume associated with type of storage device.  # noqa: E501

        :param volume_type: The volume_type of this AwsStorageProfile.  # noqa: E501
        :type: str
        """

        self._volume_type = volume_type

    @property
    def iops(self):
        """Gets the iops of this AwsStorageProfile.  # noqa: E501

        Indicates maximum I/O operations per second in range(1-20,000).  # noqa: E501

        :return: The iops of this AwsStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._iops

    @iops.setter
    def iops(self, iops):
        """Sets the iops of this AwsStorageProfile.

        Indicates maximum I/O operations per second in range(1-20,000).  # noqa: E501

        :param iops: The iops of this AwsStorageProfile.  # noqa: E501
        :type: str
        """

        self._iops = iops

    @property
    def external_region_id(self):
        """Gets the external_region_id of this AwsStorageProfile.  # noqa: E501

        The id of the region for which this profile is defined  # noqa: E501

        :return: The external_region_id of this AwsStorageProfile.  # noqa: E501
        :rtype: str
        """
        return self._external_region_id

    @external_region_id.setter
    def external_region_id(self, external_region_id):
        """Sets the external_region_id of this AwsStorageProfile.

        The id of the region for which this profile is defined  # noqa: E501

        :param external_region_id: The external_region_id of this AwsStorageProfile.  # noqa: E501
        :type: str
        """

        self._external_region_id = external_region_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AwsStorageProfile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AwsStorageProfile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
