# coding: utf-8

"""
    VMware Cloud Assembly IaaS API

    A multi-cloud IaaS API for Cloud Automation Services  # noqa: E501

    OpenAPI spec version: 2019-01-15
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Rule(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'protocol': 'str',
        'ip_range_cidr': 'str',
        'ports': 'str',
        'access': 'str'
    }

    attribute_map = {
        'name': 'name',
        'protocol': 'protocol',
        'ip_range_cidr': 'ipRangeCidr',
        'ports': 'ports',
        'access': 'access'
    }

    def __init__(self, name=None, protocol=None, ip_range_cidr=None, ports=None, access=None):  # noqa: E501
        """Rule - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._protocol = None
        self._ip_range_cidr = None
        self._ports = None
        self._access = None
        self.discriminator = None
        if name is not None:
            self.name = name
        self.protocol = protocol
        self.ip_range_cidr = ip_range_cidr
        self.ports = ports
        self.access = access

    @property
    def name(self):
        """Gets the name of this Rule.  # noqa: E501

        Name of security rule.  # noqa: E501

        :return: The name of this Rule.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Rule.

        Name of security rule.  # noqa: E501

        :param name: The name of this Rule.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def protocol(self):
        """Gets the protocol of this Rule.  # noqa: E501

        Protocol the security rule applies to.  # noqa: E501

        :return: The protocol of this Rule.  # noqa: E501
        :rtype: str
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol):
        """Sets the protocol of this Rule.

        Protocol the security rule applies to.  # noqa: E501

        :param protocol: The protocol of this Rule.  # noqa: E501
        :type: str
        """
        if protocol is None:
            raise ValueError("Invalid value for `protocol`, must not be `None`")  # noqa: E501

        self._protocol = protocol

    @property
    def ip_range_cidr(self):
        """Gets the ip_range_cidr of this Rule.  # noqa: E501

        IP address(es) in CIDR format which the security rule applies to.  # noqa: E501

        :return: The ip_range_cidr of this Rule.  # noqa: E501
        :rtype: str
        """
        return self._ip_range_cidr

    @ip_range_cidr.setter
    def ip_range_cidr(self, ip_range_cidr):
        """Sets the ip_range_cidr of this Rule.

        IP address(es) in CIDR format which the security rule applies to.  # noqa: E501

        :param ip_range_cidr: The ip_range_cidr of this Rule.  # noqa: E501
        :type: str
        """
        if ip_range_cidr is None:
            raise ValueError("Invalid value for `ip_range_cidr`, must not be `None`")  # noqa: E501

        self._ip_range_cidr = ip_range_cidr

    @property
    def ports(self):
        """Gets the ports of this Rule.  # noqa: E501

        Ports the security rule applies to.  # noqa: E501

        :return: The ports of this Rule.  # noqa: E501
        :rtype: str
        """
        return self._ports

    @ports.setter
    def ports(self, ports):
        """Sets the ports of this Rule.

        Ports the security rule applies to.  # noqa: E501

        :param ports: The ports of this Rule.  # noqa: E501
        :type: str
        """
        if ports is None:
            raise ValueError("Invalid value for `ports`, must not be `None`")  # noqa: E501

        self._ports = ports

    @property
    def access(self):
        """Gets the access of this Rule.  # noqa: E501

        Type of access (allow or deny) for the security rule. Traffic that does not match any rules will be denied.  # noqa: E501

        :return: The access of this Rule.  # noqa: E501
        :rtype: str
        """
        return self._access

    @access.setter
    def access(self, access):
        """Sets the access of this Rule.

        Type of access (allow or deny) for the security rule. Traffic that does not match any rules will be denied.  # noqa: E501

        :param access: The access of this Rule.  # noqa: E501
        :type: str
        """
        if access is None:
            raise ValueError("Invalid value for `access`, must not be `None`")  # noqa: E501
        allowed_values = ["Allow", "Deny"]  # noqa: E501
        if access not in allowed_values:
            raise ValueError(
                "Invalid value for `access` ({0}), must be one of {1}"  # noqa: E501
                .format(access, allowed_values)
            )

        self._access = access

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Rule, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Rule):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
